-- 10. 
SELECT
       DEPARTMENT_NO
     , COUNT(*)
    FROM TB_STUDENT
    GROUP BY DEPARTMENT_NO
    ORDER BY 1;

-- 11.
SELECT
       COUNT(*)
    FROM TB_STUDENT
 WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT
       SUBSTR(TERM_NO, 1, 4) 년도
     , ROUND(AVG(POINT), 1) "년도 별 평점"
    FROM TB_GRADE
 WHERE STUDENT_NO = 'A112113'
 GROUP BY SUBSTR(TERM_NO, 1, 4)
 ORDER BY 1;

-- 13.
SELECT
       DEPARTMENT_NO "학과코드명"
     , COUNT(DECODE(ABSENCE_YN, 'Y', 1, 'N', NULL)) "휴학생 수"
    FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY 1;

-- 14.
SELECT
       STUDENT_NAME "동일이름"
     , COUNT(STUDENT_NAME) "동명인 수"
    FROM TB_STUDENT
 GROUP BY STUDENT_NAME
 HAVING COUNT(STUDENT_NAME) >= 2
 ORDER BY 1;

-- 15. 
SELECT
       SUBSTR(TERM_NO, 1, 4) 년도
     , SUBSTR(TERM_NO, 5, 2) 학기
     , ROUND(AVG(POINT), 1) 평점
    FROM TB_GRADE
 WHERE STUDENT_NO = 'A112113'
 GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
 ORDER BY 1, 2;






