-- 1
SELECT
       STUDENT_NAME "학생 이름"
     , STUDENT_ADDRESS "주소지"
    FROM TB_STUDENT
 ORDER BY 1;

-- 2
SELECT
       STUDENT_NAME 
     , STUDENT_SSN
    FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY 2 DESC;

-- 3
SELECT
       STUDENT_NAME "학생이름"
     , STUDENT_NO "학번"
     , STUDENT_ADDRESS "거주지 주소"
    FROM TB_STUDENT
 WHERE (STUDENT_ADDRESS LIKE '강원%' OR STUDENT_ADDRESS LIKE '경기%')
        AND STUDENT_NO LIKE '9%'
 ORDER BY 1;

-- 4
-- ANSI 표준
SELECT 
       PROFESSOR_NAME
     , PROFESSOR_SSN
    FROM TB_PROFESSOR
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '법학과'
    ORDER BY 2;
    
-- 오라클 전용 구문
SELECT 
       PROFESSOR_NAME
     , PROFESSOR_SSN
    FROM TB_PROFESSOR P, TB_DEPARTMENT D
 WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
        AND D.DEPARTMENT_NAME = '법학과'
 ORDER BY 2;
 
-- 5
SELECT
       STUDENT_NO
     , TO_CHAR(POINT, '9.99')
    FROM TB_GRADE
 WHERE TERM_NO = '200402' 
    AND CLASS_NO = 'C3118100'
 ORDER BY 2 DESC, 1;

-- 6
-- ANSI 표준
SELECT
       STUDENT_NO
     , STUDENT_NAME
     , DEPARTMENT_NAME
    FROM TB_STUDENT 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    ORDER BY 2;
    
-- 오라클 전용 구문
SELECT
       STUDENT_NO
     , STUDENT_NAME
     , DEPARTMENT_NAME
    FROM TB_DEPARTMENT D, TB_STUDENT S
 WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO
 ORDER BY 2;
 
-- 7
-- ANSI 표준
SELECT
       CLASS_NAME
     , DEPARTMENT_NAME
    FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- ORACLE 전용 구문
SELECT 
       CLASS_NAME
     , DEPARTMENT_NAME
    FROM TB_CLASS C, TB_DEPARTMENT D
 WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO;








